---
title: "cl_02_fruitnut_cnty"
author: "Yuanyuan Wen"
date: "2026-07-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

Compute each county's fruit & nut share = (county fruit & nut sales) / (county total farm-related income receipts), using USDA-NASS data. The share is used to identify counties dominated by fruit & nut production.

```{r Library}
library(rnassqs)
library(tidyverse)
```

# API Setup
```{r API}
# nassqs_auth(key = "your NASS API")

```

# Fetch Fruit & Nut Data
```{r Fetch Data}
df_fruitnut <- nassqs(list(
  commodity_desc = "FRUIT & TREE NUT TOTALS",
  agg_level_desc = "COUNTY",
  year__GE       = 2022,
  short_desc = "FRUIT & TREE NUT TOTALS - SALES, MEASURED IN $",
  domain_desc = "TOTAL"
)) 

df_fruitnut$fips <- paste0(df_fruitnut$state_fips_code,df_fruitnut$county_code)  
length(unique(df_fruitnut$fips))

df_fruitnut <- df_fruitnut %>% select(fips,Value,county_name,state_name) %>% rename(fruitnut_sale=Value)
```

# Fetch Farm Income Data

```{r Total farm receipts}
df_farm_ttl <- nassqs(list(
  commodity_desc = "INCOME, FARM-RELATED",
  agg_level_desc = "COUNTY",
  year__GE       = 2022,
  domain_desc = "TOTAL",
  short_desc = "INCOME, FARM-RELATED - RECEIPTS, MEASURED IN $"
))
df_farm_ttl$fips <- paste0(df_farm_ttl$state_fips_code,df_farm_ttl$county_code)  
length(unique(df_farm_ttl$fips))

df_farm_ttl <- df_farm_ttl %>% select(fips,Value,county_name,state_name) %>% rename(farm_sale=Value)


```

# Merge

```{r Merge}
df_merge <- merge(df_farm_ttl,df_fruitnut,by="fips",all=TRUE)
```


# Calculate share
```{r Share calculate}
df_merge$share <- df_merge$fruitnut_sale/df_merge$farm_sale
df_merge <- df_merge %>% select(-county_name.y,-state_name.y)
```

# Save
```{r Save Data}
write.csv(df_merge,"../data/outcome/fruitnut_share.csv")
```
