---
title: "an_01b_spma_index"
author: "Xiaoyi Zhao"
date: "2026-07-15"
output: html_document
---
## Purpose

This code produce the first multi-state comparison 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


### Step 1 — read the dataset with index
```{r}
spma_index <- read_csv("../data/outcome/spma_index.csv") 
```



### Step 4b - Food hub location
```{r}
drop_fp <- c("02", "15", "60", "66", "69", "72", "78")

foodhub_raw <- read_excel("../data/source/foodhub_2026-75161420.xlsx")

foodhub_directory <- foodhub_raw %>%
  select(listing_id, listing_name, location_x, location_y, products) %>%
  rename(lon = location_x, lat = location_y) %>%
  mutate(lon = as.numeric(lon),
         lat = as.numeric(lat)) %>%
  filter(!is.na(lon), !is.na(lat))

hubs_sf <- st_as_sf(foodhub_directory, coords = c("lon", "lat"), crs = 4326)

county_lookup <- counties(cb = TRUE, year = 2023, progress_bar = FALSE) %>%
  select(STATEFP, GEOID, county_name = NAME) %>%
  st_transform(4326)

hubs_pts <- st_join(hubs_sf, county_lookup, join = st_within) %>%
  filter(!STATEFP %in% drop_fp) %>%
  st_transform(5070)

```



### Step 5 — US county choropleth
```{r}
# lower-48 + DC county polygons (drop AK/HI/territories)
counties_sf <- counties(cb = TRUE, year = 2023, progress_bar = FALSE) %>%
  filter(!STATEFP %in% drop_fp) %>%
  transmute(county_fips = GEOID) %>%
  st_transform(5070)

states_sf <- states(cb = TRUE, year = 2023, progress_bar = FALSE) %>%
  filter(!STATEFP %in% drop_fp) %>%
  select(NAME) %>%
  st_transform(5070)

map_df <- counties_sf %>%
  left_join(spma_index, by = "county_fips")


```

load the font that we want to use for the figures
```{r}
# using serif display as the title font 
font_add_google(
  name = "DM Serif Display",
  family = "title_font"
)

# using dm sans as the body font 
font_add_google(
  name = "DM Sans",
  family = "body_font"
)

# keep this open so that the figure will return the fonts that we set 
showtext::showtext_auto(TRUE)
```

```{r}
# specify the map color style 
map_color <- colorRampPalette(c("#EFF6FF", "#C7D2FE", "#A5B4FC",
                             "#7C3AED", "#4C1D95"))

fig_01c_annotated <- ggplot(map_df) +
  geom_sf(aes(fill = SPMA_0_100), color = NA) + 
  geom_sf(data = states_sf, fill = NA, color = "grey55", linewidth = 0.25) + 
  geom_sf(
  data = hubs_pts,
  shape = 21,
  fill = "#c8ff88",
  color = "#15803D",
  size = 2.4,
  stroke = 0.4,
  alpha = 0.85
) +
  scale_fill_gradientn(
  colours = map_color(100),        
  limits  = c(0, 100),
  oob     = scales::squish,
  labels  = scales::label_number(accuracy = 1),
  na.value = "grey90",
  name    = "SPMA\n(0-100)"
)  + 
  coord_sf(crs = 5070) +
  theme_void(base_family = "body_font") +
  labs(
    title = "Small-Producers' Market Accessibility(SPMA)",
    subtitle = paste0(
      "How market access connects fruit and tree nut producers ",
      "to consumers and food hubs"
    )
  ) +
  theme(
    plot.background = element_rect(
      fill = "#FAF8F2",
      color = NA
    ),
    panel.background = element_rect(
      fill = "#FAF8F2",
      color = NA
    ),

    plot.title = element_text(
      family = "title_font",
      size = 25,
      lineheight = 0.88,
      color = "#123B65",
      face = "plain",
      hjust = 0,
      margin = margin(b = 1)
    ),

    plot.subtitle = element_text(
      family = "body_font",
      size = 12,
      lineheight = 1.2,
      color = "#4B5D6D",
      hjust = 0,
      margin = margin(b = 10)
    ),

    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.key.width = unit(2.5, "cm"),
    legend.key.height = unit(0.28, "cm"),

    plot.margin = margin(
  t = 10,
  r = 10,
  b = 10,
  l = 10
)
  )
```

This adds the text by the map so that the information w want to deliver are more straight forward
```{r}

# this note appears on the right hand side of the map 
notes_panel <- ggplot() +
  annotate(
    "text",
    x = 0,
    y = 0.92,
    label = "Food hubs expand market access",
    hjust = 0,
    vjust = 1,
    family = "body_font",
    fontface = "bold",
    size = 5.2,
    color = "#123B65"
  ) +
  annotate(
    "text",
    x = 0,
    y = 0.82,
    label = paste0(
      "Counties closer to food hubs tend to have\n",
      "stronger access to markets and buyers.\n",
      "Yellow dots identify food hub locations."
    ),
    hjust = 0,
    vjust = 1,
    family = "body_font",
    size = 4,
    lineheight = 1.15,
    color = "#4B5D6D"
  ) +
  annotate(
    "segment",
    x = -0.06,
    xend = -0.06,
    y = 0.75,
    yend = 0.96,
    linewidth = 1.4,
    color = "#c8ff88"
  ) +
  annotate(
    "text",
    x = 0,
    y = 0.58,
    label = "Accessibility is multidimensional",
    hjust = 0,
    vjust = 1,
    family = "body_font",
    fontface = "bold",
    size = 5.2,
    color = "#123B65"
  ) +
  annotate(
    "text",
    x = 0,
    y = 0.48,
    label = paste0(
      "The SPMA combines direct-to-consumer access,\n",
      "food-hub connections, and market proximity.\n",
      "Darker blue represents higher accessibility."
    ),
    hjust = 0,
    vjust = 1,
    family = "body_font",
    size = 4,
    lineheight = 1.15,
    color = "#4B5D6D"
  ) +
  annotate(
    "segment",
    x = -0.06,
    xend = -0.06,
    y = 0.41,
    yend = 0.62,
    linewidth = 1.4,
    color = "#3182BD"
  ) +
  coord_cartesian(
    xlim = c(-0.1, 1),
    ylim = c(0, 1),
    clip = "off"
  ) +
  theme_void() +
  theme(
    plot.background = element_rect(
      fill = "#FAF8F2",
      color = NA
    )
  )

# this note explains the potential reasons for the missing values in the middle 
rural_note <- ggplot() +
  annotate(
    "segment",
    x = 0.02,
    xend = 0.02,
    y = 0.12,
    yend = 0.88,
    linewidth = 1.5,
    color = "#A7B6C5"
  ) +
  annotate(
    "text",
    x = 0.07,
    y = 0.84,
    label = "Why are values missing in the central U.S.?",
    hjust = 0,
    vjust = 1,
    family = "body_font",
    fontface = "bold",
    size = 4,
    color = "#123B65"
  ) +
  annotate(
    "text",
    x = 0.07,
    y = 0.62,
    label = paste0(
      "Missing SPMA values mainly reflect unavailable or suppressed sales data.\n",
      "These gaps are more common in rural counties and places with fewer fruit\n",
      "and tree nut farms."
    ),
    hjust = 0,
    vjust = 1,
    family = "body_font",
    size = 3,
    lineheight = 1.15,
    color = "#4B5D6D"
  ) +
  coord_cartesian(
    xlim = c(0, 1),
    ylim = c(0, 1),
    clip = "off"
  ) +
  theme_void() +
  theme(
    plot.background = element_rect(
      fill = "#FAF8F2",
      color = NA
    ),
    plot.margin = margin(5, 10, 5, 20)
  )

```

Combine the map with the notes
```{r}
left_column <- fig_01c_annotated / rural_note +
  plot_layout(
    heights = c(4.5, 1)
  )


final_layout <- (left_column | notes_panel) +
  patchwork::plot_layout(
    ncol = 2,
    widths = c(3.2, 1.25)
  ) +
  plot_annotation(
    theme = theme(
      plot.background = element_rect(
        fill = "#FAF8F2",
        color = NA
      ),
      plot.title = element_text(
        family = "title_font",
        size = 34,
        lineheight = 0.88,
        color = "#123B65",
        hjust = 0,
        margin = margin(b = 12)
      ),
      plot.subtitle = element_text(
        family = "body_font",
        size = 14,
        color = "#4B5D6D",
        hjust = 0,
        margin = margin(b = 18)
      ),
      plot.margin = margin(
        t = 30,
        r = 35,
        b = 25,
        l = 35
      )
    )
  )


ggsave("../figures/fig_01.pdf", plot = final_layout, width = 18, height = 8)

```


