---
title: "fig_01_xz"
author: "Xiaoyi Zhao"
date: "2026-07-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

The goal of this file to build the first candidate of the visualation, 

this will be by state level, and we will plot the market accessibility by state 


load the libraries
```{r}
library(tigris)    # downloads Census TIGER shapefiles (county boundaries)
library(sf)        # the workhorse: stores and manipulates spatial data
library(dplyr)     # regular data wrangling once things look like data frames

library(ggplot2)
library(mapview)
library(readxl)
library(units)
```


load the dataset we merged 
```{r}
merged_final <- read_csv("../data/outcome/merged_final_xz.csv") %>% 
  select(state, spma) %>% 
  group_by(state) %>% 
  summarize(
    spma = mean(spma, na.rm = TRUE)
  ) %>% 
  mutate(state = tolower(state))
  # we ignore the missing data here 
```

Plot the figure : 

```{r}

# first, we load the us state level map with simple boundaries

state_map <- states(cb = TRUE) %>% 
  filter(!STUSPS %in% c("AK", "HI", "PR", "GU", "VI", "AS", "MP"))
```
step 2: join the index with the map 
```{r}
index_map <- state_map %>% 
  mutate(state_lower = tolower(NAME)) %>%  # to match with our statename
  left_join(merged_final, by = c("state_lower" = "state"))
```


step 3: graph the first figure:

```{r}
index_map <- index_map %>%
  mutate(spma_scaled = 100 * spma / max(spma, na.rm = TRUE))

ggplot2::ggplot(index_map) +
  geom_sf(aes(fill = spma_scaled), color = "grey70", linewidth = 0.2) +
   scale_fill_distiller(
  palette   = "Reds",
  direction = 1,                    # 1 = darker for larger
  trans     = "log10",
  labels    = scales::label_number(accuracy = 0.1),
  na.value  = "grey88",
  name      = "SPMA\n(log scale)"
) +
  coord_sf(crs = 5070) +           # Albers Equal Area projection
  labs(
    title    = "Small-Producer Market Access (SPMA) Index, State Means",
    subtitle = "Higher = better weighted access to farmers markets & food hubs",
    caption  = "Gray = no data. Index rescaled to 0–100 relative to the highest state."
  ) +
  theme_void() +
  theme(
    plot.title      = element_text(face = "bold", size = 14, hjust = 0),
    plot.subtitle   = element_text(size = 11, color = "grey30",
                                   margin = margin(b = 10)),
    plot.caption    = element_text(size = 8, color = "grey40", hjust = 0),
    legend.position = c(0.92, 0.30),
    legend.title    = element_text(size = 9),
    legend.text     = element_text(size = 8),
    plot.margin     = margin(10, 10, 10, 10)
  )
```
step 4: overlay this with the hot splot of foodhub 

load the foodhub locations
```{r}
foodhub_raw <- read_excel("../data/source/foodhub_2026-75161420.xlsx") 

foodhub_directory <- foodhub_raw %>% 
  select(listing_id, listing_name, location_x, location_y, products) %>% 
  rename(lon = location_x, lat = location_y) %>% 
  mutate(lon = as.numeric(lon), 
         lat = as.numeric(lat)) %>% 
  filter(!is.na(lon), !is.na(lat)) 

hubs_sf <- st_as_sf(foodhub_directory, coords = c("lon", "lat"), crs = 4326)

us_counties <- counties(cb = TRUE, year = 2023)

county_lookup <- us_counties %>%
  select(STATEFP, GEOID, county_name = NAME) %>%   # select() can rename in-place
  st_transform(4326) 

hubs_geo <- st_join(hubs_sf, county_lookup, join = st_within)

hubs_pts <- st_transform(hubs_geo) %>% 
  filter(!STATEFP %in% c("02", "15"))                           # exclude Hawaii and Alaska

```

```{r, fig.width= 12, fig.height = 5}
index_map <- index_map %>%
  mutate(spma_scaled = 100 * spma / max(spma, na.rm = TRUE))

fig_1 <- ggplot2::ggplot(index_map) +
  geom_sf(aes(fill = spma_scaled), color = "grey70", linewidth = 0.2) +
  geom_sf(data = hubs_pts, shape = 21, fill = "pink",
        color = "white", size = 2.2, stroke = 0.4) +
   scale_fill_distiller(
  palette   = "Reds",
  direction = 1,                    # 1 = darker for larger
  trans     = "log10",
  labels    = scales::label_number(accuracy = 0.1),
  na.value  = "grey88",
  name      = "SPMA\n(log scale)"
) +
  coord_sf(crs = 5070) +           # Albers Equal Area projection
  labs(
    title    = "Small-Producer Market Access (SPMA) Index, State Means",
    subtitle = "Higher = better weighted access to farmers markets & food hubs",
    caption  = "Gray = no data. Index rescaled to 0–100 relative to the highest state. Pink Dots = the location of Foodhubs"
  ) +
  theme_void() +
  theme(
    plot.title      = element_text(face = "bold", size = 14, hjust = 0),
    plot.subtitle   = element_text(size = 11, color = "grey30",
                                   margin = margin(b = 10)),
    plot.caption    = element_text(size = 8, color = "grey40", hjust = 0),
    legend.position = c(0.92, 0.30),
    legend.title    = element_text(size = 9),
    legend.text     = element_text(size = 8),
    plot.margin     = margin(10, 10, 10, 10)
  )
```

```{r}
ggsave("../figures/fig_01_xz.pdf", plot = fig_1, width = 12, height = 5)
```

